### DISCUSSION TITLE
Configure i18n-ally to work with the package

### DISCUSSION THREAD

**Discussion by Jon1VK** [Jon1VK/NextGlobeGen#236] [Ideas]
Configure next-globe-gen playground example to work with [i18n-ally](https://github.com/lokalise/i18n-ally/tree/main) locally and provide the configuration in a PR to be tested by others. After the configuration has been tested to work, make a PR to i18n-ally so that the next-globe-gen can be easily integrated with i18n-ally extension by other users.

Check https://github.com/lokalise/i18n-ally/wiki/Custom-Framework and https://github.com/lokalise/i18n-ally/tree/main/src/frameworks for example integrations.

**Comment by takayumi** [comment]
For anyone using this super useful library, the following config worked for me assuming you followed the [NextGlobeGen tutorial](https://next-globe-gen.dev/docs/getting-started):

```yaml
# .vscode/i18n-ally-custom-framework.yml
languageIds:
  - javascript
  - typescript
  - javascriptreact
  - typescriptreact

# An array of RegExes to find the key usage. **The key should be captured in the first match group**.
# You should unescape RegEx strings in order to fit in the YAML file
# To help with this, you can use https://www.freeformatter.com/json-escape.html
usageMatchRegex:
  # The following example shows how to detect `t("your.i18n.keys")`
  # the `{key}` will be placed by a proper keypath matching regex,
  # you can ignore it and use your own matching rules as well
  - "[^\\w\\d]t\\(['\"`]({key})['\"`]"

# A RegEx to set a custom scope range. This scope will be used as a prefix when detecting keys
# and works like how the i18next framework identifies the namespace scope from the
# useTranslation() hook.
# You should unescape RegEx strings in order to fit in the YAML file
# To help with this, you can use https://www.freeformatter.com/json-escape.html
scopeRangeRegex: "useTranslation\\(\\s*\\[?\\s*['\"`](.*?)['\"`]"

# An array of strings containing refactor templates.
# The "$1" will be replaced by the keypath specified.
# Optional: uncomment the following two lines to use

# refactorTemplates:
#  - i18n.get("$1")


# If set to true, only enables this custom framework (will disable all built-in frameworks)
monopoly: true
```

Also sidenote; thank you so much for the library, @Jon1VK! I really disliked how next-intl needed middleware to remove default the locale prefix. Your library just works & is extremely pluggable.
